### ISSUE TITLE
live tile error when compiling and debugging

### ISSUE THREAD

**Issue by ghost** [StartNine/DoubleDeckerBar#4]
System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=Could not find a part of the path 'C:\Program Files\WindowsApps\Microsoft.BingTravel_3.0.4.212_x64__8wekyb3d8bbwe\AppxManifest.xml'.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at Start9.Api.Tools.AppxTools.GetUpdateAddressFromApp(String app) in E:\Start9\Start9.Api-master (2)\Start9.Api-master\Start9.Api\Tools\AppxTools.cs:line 218
   at Start9.Api.Tools.AppxTools.TileInfo..ctor(String App) in E:\Start9\Start9.Api-master (2)\Start9.Api-master\Start9.Api\Tools\AppxTools.cs:line 173
   at DoubleDeckerBar.MainWindow.MainWindow_Loaded(Object sender, RoutedEventArgs e) in E:\Start9\DoubleDeckerBar-master (99)\DoubleDeckerBar-master\DoubleDeckerBar\MainWindow.xaml.cs:line 343
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

Error when debugging with the live tile

**Comment by ghost** [comment]
Help

**Comment by ghost** [comment]
OS is windows 8.1

**Comment by Splitwirez** [comment]
Do you have the Travel app?

**Comment by ghost** [comment]
I will check

**Comment by ghost** [comment]
its not on the windows store but yes
![image](https://user-images.githubusercontent.com/37509156/38786306-b2dc0dd8-40ec-11e8-8353-4be736e66a70.png)

**Comment by Splitwirez** [comment]
Different version of the app, apparently. That would explain it. Ultimately that won't be an issue though, it's just that for the moment, I hardcoded it to my app because getting Tile Notifications works currently, but getting apps to begin with doesn't even exist yet.

**Comment by ghost** [comment]
oh ok how do i get it working

**Comment by Splitwirez** [comment]
...I literally just said that the problem is on my end, as a byproduct of how I was testing stuff ._.

**Comment by ghost** [comment]
oh its on your end
